version: '3.8'

services:
  nextapp:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PG_USER: postgres
      # PG_PASSWORD: your_db_password if you need
      PG_DATABASE: project_management
      PG_HOST: db
      PG_PORT: 5432
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      # POSTGRES_PASSWORD: password
      POSTGRES_DB: project_management
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
